### ISSUE TITLE
LV2 Vitalium settings do not restore correctly when a project is saved and reopened

### ISSUE THREAD

**Issue by loplkc** [DISTRHO/DISTRHO-Ports#96] opened 2021-08-20 03:40 UTC
This is supposedly a known issue regarding the fork of JUCE that Vitalium's LV2 version uses. In the DAWs I have used (Ardour and Zrythm), projects with Vitalium LV2 instances will often have those instances altered when the projects are reopened. The settings of some instances are randomly changed, ruining the patches. The only way to deal with this is to use the VST3 plugin (which is laggier in Zrythm and more prone to crashing in Ardour), or to manually save every instance as its own patch before closing a project and set them back to those patches when reopening the project. I do not know what conditions are required for this issue to manifest, but I have found other people who have experienced it. I am using the plugin on Arch Linux through the distrho-ports Arch package.

**Comment by plainoldcheese** [comment] 2021-09-20 12:04
I also have these issues with Vitalium and some other lv2 plugins. On arch linux in Reaper

**Comment by mycroftsnm** [comment] 2022-01-07 22:02
Same issue here, Arch linux and reaper, with the arch repository package

**Comment by jcelerier** [comment] 2022-01-12 13:34
Can confirm the same on ossia score. Official "Vital.so" VST3 from ArchLinux package vital-synth does reload correctly.

**Comment by ZhekaHauska** [comment] 2022-01-17 15:48
I have the same issue with Vitalium on Manjaro. I have to pick again every instrument preset after Ardour, LMMS restart since settings are altered.

**Comment by magnetophon** [comment] 2022-01-29 16:11
Same here, with Vitalium in Ardour, using NixOS.

**Comment by loplkc** [comment] 2022-03-30 00:56
I am now on Debian (same machine) and have Vitalium installed from the kxstudio repository. The issue still persists.

**Comment by nengisuls** [comment] 2022-04-01 21:07
Same here.  Vitalium in Ardour 6.9 on Linux Mint.  I've opted to save the presets and reload for the moment.  Is there any other logs or info I can provide devs to help resolve this?  Sorry, I'm new to contributing to bug tracking.

**Comment by falkTX** [comment] 2022-04-01 21:14
Does the same happen with swankyamp from disthro-ports? It is made with the same juce version as vitalium, would help to find out where the issue is.

**Comment by nengisuls** [comment] 2022-04-02 04:22
I was able to save states in swankyamp lv2.  BTW both my versions are from the kx studio repo, if that helps.

**Comment by CameronAsselin** [comment] 2022-07-31 12:13
Also having this issue on Arch using Reaper as a DAW.

vital-synth on the AUR has graphical issues when closing the patch bay and then reopening it and will often crash Reaper, and downloading Vital off the website and placing the files in my .vst folder will cause Reaper to crash if I save, close, and then reopen. So far, distrho-ports runs the best by far, but having to reload the patches every time I close the software is cumbersome.

**Comment by DarkRTA** [comment] 2023-01-23 02:00
This seems like a bit of a race condition.
Loading a patch caused vitalium to change a large number of its parameters at once, and some hosts choke on this and end up missing some of the changes, resulting in what vitalium has being out of sync with what the daw has.

If I modify a parameter by hand after loading the patch,

**Comment by xard-dev** [comment] 2023-02-25 22:26
I can also confirm this. 

Though for a race condition the symptoms are very systematic. For example when loading a project with LV2 instance using certain patches the patches always fail in same way when reloading the project.

**Closed** 2024-05-01 05:01 UTC
